//This js file contains the quotes

let quotes_list = [];

//quote object constructor
function quote(quote_input, author) {
    this.the_quote = quote_input;
    this.quote_author = author;
}

export function Quote_list_initialisation() {
    //Quote database
    quotes_list = [
        new quote("Has it ever struck you that life is all memory, except for the one present moment that goes by you so quick you hardly catch it going?","Tennessee Williams"),
        new quote("In a world filled with hate, we must still dare to hope.","Michael Jackson"),
        new quote("Lies run sprints, but the truth runs marathons.","Michael Jackson"),
        new quote("To give someone a piece of your heart, is worth more than all the wealth in the world.","Michael Jackson"),
        new quote("A star can never die. It just turns into a smile and melts back into the cosmic music, the dance of life.","Michael Jackson"),
        new quote('To belittle you have to be little','Khalil Gibran'),
        new quote("Do, or do not. There is no 'try'","Yoda"),
        new quote("When things go wrong, don't go with them.","Elvis Presley"),
        new quote("Truth is like the sun. You can shut it out for a time, but it ain't going away.","Elvis Presley"),
        new quote("If you let your head get too big, it'll break your neck.","Elvis Presley"),
        new quote("It ain’t about how hard you can hit. It’s about how hard you can get hit and keep moving forward.","Rocky Balboa"),
        new quote("To judge a man by his weakest link or deed is like judging the power of the ocean by one wave.","Elvis Presley"),
        new quote("The man who views the world at 50 the same as he did at 20 has wasted 30 years of his life.","Muhammad Ali"),
        new quote("Some mountains are higher than others, some roads steeper than the next. There are hardships and setbacks, but you can't let them stop you. ","Muhammad Ali"),
        new quote("The hero and the coward both feel the same thing. But the hero uses his fear, projects it onto his opponent, while the coward runs. It’s the same thing, fear, but it’s what you do with it that matters.","Cus D'amato"),
        new quote('The battleline between good and evil runs through the heart of every man.','Aleksandr Solzhenitsyn'),
        new quote('Defeat, my Defeat, my solitude and my aloofness. You are dearer to me than a thousand triumphs, and sweeter to my heart than all world-glory.','Khalil Gibran'),
        new quote('Trust in dreams, for in them is hidden the gate to eternity.','Khalil Gibran'),
        new quote("Yesterday is but today's memory, and tomorrow is today's dream.",'Khalil Gibran'),
        new quote('Your pain is the breaking of the shell that encloses your understanding.','Khalil Gibran'),
        new quote('The fault, dear Brutus, is not in our stars, but in ourselves.','William Shakespeare'),
        new quote("I'm thankful for women. I think they are more intelligent than men. Also, without women, there would be no cookies.","Norm Macdonald"),
        new quote('We know what we are, but not what we may be.','William Shakespeare'),
        new quote('Some are born great, others achieve greatness.','William Shakespeare'),
        new quote("I have come here to chew bubblegum and kick ass...and I'm all out of bubblegum", 'Duke Nukem'),
        new quote("Say 'ello to my little friend!", 'Tony Montana'),
        new quote("Those who have a 'why' to live, can bear with almost any 'how'.",'Viktor Frankl'),
        new quote('The fool doth think he is wise, but the wise man knows himself to be a fool','William Shakespeare'),
        new quote('What the superior man seeks is in himself; what the small man seeks is in others.','Confucius'),
        new quote('Our greatest glory is not in never falling, but in rising every time we fall.','Confucius'),
        new quote('It does not matter how slowly you go so long as you do not stop.','Confucius'),
        new quote('The secret of life, though, is to fall seven times and to get up eight times.','Paulo Coelho'),
        new quote('Veni Vidi Vici','Julius Caesar'),
        new quote("Hey WNBA I got an idea that will sell some tickets, shirts and skins", "Norm Macdonald"),
        new quote('The beginnings of all things are small.','Roman proverb'),
        new quote('There is only one thing that makes a dream impossible to achieve: the fear of failure.','Paulo Coelho'),
        new quote('Deep into that darkness peering, long I stood there, wondering, fearing, doubting, dreaming dreams no mortal ever dared to dream before.','Edgar Allan Poe'),
        new quote('To live is to suffer, to survive is to find some meaning in the suffering.','Friedrich Nietzsche'),
        new quote('Hope in reality is the worst of all evils because it prolongs the torments of man.','Friedrich Nietzsche'),
        new quote('Nothing great in the world was accomplished without passion.','Georg Wilhelm Friedrich Hegel'),
        new quote('We learn from history that we do not learn from history.','Georg Wilhelm Friedrich Hegel'),
        new quote('Genuine tragedies in the world are not conflicts between right and wrong. They are conflicts between two rights','Georg Wilhelm Friedrich Hegel'),
        new quote('Truth is found neither in the thesis nor the antithesis, but in an emergent synthesis which reconciles the two.','Georg Wilhelm Friedrich Hegel'),
        new quote('The valor that struggles is better than the weakness that endures.','Georg Wilhelm Friedrich Hegel'),
        new quote('That which does not kill us makes us stronger.','Friedrich Nietzsche'),
        new quote("More than machinery, we need humanity. More than cleverness, we need kindness and gentleness. Without these qualities life will be violent and all will be lost.", "Charlie Chaplin"),
        new quote('There are no beautiful surfaces without a terrible depth.','Friedrich Nietzsche'),
        new quote('Ask and it will be given to you; seek and you will find; knock and the door will be opened to you. For everyone who asks receives; the one who seeks finds; and to the one who knocks, the door will be opened.','Jesus Christ'),
        new quote('Blessed are the merciful for they will be shown mercy.','Jesus Christ'),
        new quote('Talent hits a target no one else can hit. Genius hits a target no one else can see.','Arthur Schopenhauer'),
        new quote('Mostly it is loss which teaches us about the worth of things.','Arthur Schopenhauer'),
        new quote('A man can be himself only so long as he is alone; and if he does not love solitude, he will not love freedom; for it is only when he is alone that he is really free.','Arthur Schopenhauer'),
        new quote('One should use common words to say uncommon things','Arthur Schopenhauer'),
        new quote('Great men are like eagles, and build their nest on some lofty solitude.','Arthur Schopenhauer'),
        new quote('Hope is the confusion of the desire for a thing with its probability.','Arthur Schopenhauer'),
        new quote('The safest way of not being very miserable is not to expect to be very happy.','Arthur Schopenhauer'),
        new quote('Change alone is eternal, perpetual, immortal.','Arthur Schopenhauer'),
        new quote("Pop singer Madonna was outraged this week when a photographer snapped her picture while she was breastfeeding her new baby. Apparently the baby was blocking her nipple.", "Norm Macdonald"),
        new quote('We seldom think of what we have, but always of what we lack.','Arthur Schopenhauer'),
        new quote('Life can only be understood backwards; but it must be lived forwards.','Soren Kierkegaard'),
        new quote('People demand freedom of speech as a compensation for the freedom of thought which they seldom use.','Soren Kierkegaard'),
        new quote('Life is not a problem to be solved, but a reality to be experienced.','Soren Kierkegaard'),
        new quote('Marry, and you will regret it; do not marry, you will also regret it; marry or don’t marry, you will regret it either way.','Soren Kierkegaard'),
        new quote('Face the facts of being what you are, for that is what changes what you are.','Soren Kierkegaard'),
        new quote("To go wrong in one's own way is better than to go right in someone else's.",'Fyodor Dostoevsky'),
        new quote('It takes something more than intelligence to act intelligently.','Fyodor Dostoevsky'),
        new quote('Nothing in this world is harder than speaking the truth, nothing easier than flattery.','Fyodor Dostoevsky'),
        new quote('You can be sincere and still be stupid.','Fyodor Dostoevsky'),
        new quote("You me or nobody is going to hit as hard as life. But it ain't about how hard you hit. It's about how hard you can get hit and keep moving forward","Rocky Balboa"),
        new quote("To be or not to be that is the question", "William Shakespeare"),
        new quote('Attitude is a choice. Happiness is a choice. Optimism is a choice. Kindness is a choice. Giving is a choice. Respect is a choice. Whatever choice you make makes you. Choose wisely.','Roy T. Bennett'),
        new quote("Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",'Roy T. Bennett'),
        new quote('Instead of worrying about what you cannot control, shift your energy to what you can create.','Roy T. Bennett'),
        new quote('If you want to fly, you have to give up what weighs you down.','Roy T. Bennett'),
        new quote('Becoming a great leader does not mean being perfect. it means living with your imperfections.','Lolly Daskal'),
        new quote('To improve is to change, so to be perfect is to change often.','Winston Churchill'),
        new quote('The price of greatness is responsibility.','Winston Churchill'),
        new quote('I love the smell of napalm in the morning.','Lieutenant Kilgore'),
        new quote('You have enemies? Good. That means you’ve stood up for something in your life.','Winston Churchill'),
        new quote('Success is the ability to go from one failure to another with no loss of enthusiasm.','Winston Churchill'),
        new quote('I like things to happen, and if they don’t happen I like to make them happen.','Winston Churchill'),
        new quote('What is adequacy? Adequacy is no standard at all.','Winston Churchill'),
        new quote('Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.','Martin Luther King jr.'),
        new quote('Our lives begin to end the day we become silent about things that matter.','Martin Luther King jr.'),
        new quote('I did not have sexual relations with that woman','Bill Clinton'),
        new quote('The best books... are those that tell you what you know already.','George Orwell'),
        new quote('Who controls the past controls the future. Who controls the present controls the past.','George Orwell'),
        new quote('Is it better for a man to have chosen evil than to have good imposed upon him?','Anthony Burgess'),
        new quote('One day, in retrospect, the years of struggle will strike you as the most beautiful.','Sigmund Freud'),
        new quote('Most people do not really want freedom, because freedom involves responsibility, and most people are frightened of responsibility.','Sigmund Freud'),
        new quote('Everything that irritates us about others can lead us to an understanding of ourselves.','Carl Gustav Jung'),
        new quote("You are what you do, not what you say you'll do.",'Carl Gustav Jung'),
        new quote('The privilege of a lifetime is to become who you truly are.','Carl Gustav Jung'),
        new quote("There's no coming to consciousness without pain.",'Carl Gustav Jung'),
        new quote('Mistakes are, after all, the foundations of truth, and if a man does not know what a thing is, it is at least an increase in knowledge if he knows what it is not. ','Carl Gustav Jung'),
        new quote('Thinking is difficult, that’s why most people judge.','Carl Gustav Jung'),
        new quote('We cannot change anything unless we accept it.','Carl Gustav Jung'),
        new quote('The first half of life is devoted to forming a healthy ego, the second half is going inward and letting go of it.','Carl Gustav Jung'),
        new quote('Wholeness is not achieved by cutting off a portion of one’s being, but by integration of the contraries.','Carl Gustav Jung'),
        new quote('Who looks outside, dreams; who looks inside, awakes.','Carl Gustav Jung'),
        new quote("Trees are poems the earth writes upon the sky, We fell them down and turn them into paper, so that we may record our emptiness.","Khalil Gibran"),
        new quote("Out of suffering have emerged the strongest souls; the most massive characters are seared with scars.","Khalil Gibran"),
        new quote("Tenderness and kindness are not signs of weakness and despair, but manifestations of strength and resolution.","Khalil Gibran"),
        new quote("Some of you say, “Joy is greater than sorrow,” and others say, “Nay, sorrow is the greater.” But I say unto you, they are inseparable. Together they come, and when one sits alone with you at your board, remember that the other is asleep upon your bed.","Khalil Gibran"),
        new quote("Generosity is giving more than you can, and pride is taking less than you need.","Khalil Gibran"),
        new quote("The smallest act of kindness is worth more than the greatest intention.","Khalil Gibran"),
        new quote("Solitude has soft, silky hands, but with strong fingers it grasps the heart and makes it ache with sorrow.","Khalil Gibran"),
        new quote("An eye for an eye, and the whole world would be blind.","Khalil Gibran"),
        new quote("The deeper that sorrow carves into your being, the more joy you can contain.","Khalil Gibran"),
        new quote("Desire is half of life; indifference is half of death.","Khalil Gibran"),
        new quote("Under the White Cliff’s battlemented crown, Hushed to a depth of more than Sabbath peace.","William Wordsworth"),
        new quote("It is not the mountain we conquer but ourselves.","Sir Edmund Hillary"),
        new quote("If there are no dogs in Heaven, then when I die I want to go where they went.","Will Rogers"),
        new quote("When you find yourself in a hole, quit digging.","Will Rogers"),
        new quote("Money, if it does not bring you happiness, will at least help you be miserable in comfort.","Helen Gurley Brown"),
        new quote("Wealth consists not in having great possessions, but in having few wants.","Epictetus"),
        new quote("Create with the heart; build with the mind.","Criss Jami"),
        new quote("The purpose of education is to replace an empty mind with an open one.","Malcolm Forbes"),
        new quote("All that glisters is not gold; often have you heard that told.","William Shakespeare"),
        new quote("I don't like to commit myself about Heaven and Hell, you see, I have friends in both places.","Mark Twain"),
        new quote("It is nationalism which engenders nations, and not the other way round.","Ernest Gellner"),
        new quote("Never was anything great achieved without danger.","Niccolo Machiavelli"),
        new quote("He who wishes to be obeyed must know how to command","Niccolo Machiavelli"),
        new quote("Few men are born brave, many become so through training and force of discipline.","Vegetius"),
        new quote("All men make mistakes, but a good man yields when he knows his course is wrong, and repairs the evil. The only crime is pride.","Sophocles"),
        new quote("Fortune is not on the side of the faint-hearted.","Sophocles"),
        new quote("A man, though wise, should never be ashamed of learning more, and must unbend his mind.","Sophocles"),
        new quote("Fear? What has a man to do with fear? Chance rules our lives, and the future is all unknown. Best live as we may, from day to day.","Sophocles"),
        new quote("Wisdom outweighs any wealth.","Sophocles"),
        new quote("Knowing yourself is the beginning of all wisdom.","Aristotle"),
        new quote("It is the mark of an educated mind to be able to entertain a thought without accepting it.","Aristotle"),
        new quote("Educating the mind without educating the heart is no education at all.","Aristotle"),
        new quote("No great mind has ever existed without a touch of madness.","Aristotle"),
        new quote("A friend to all is a friend to none.","Aristotle"),     
        new quote("Patience is bitter, but its fruit is sweet.","Aristotle"),
        new quote("He who has overcome his fears will truly be free.","Aristotle"),
        new quote("The more you know, the more you know you don't know.","Aristotle"),
        new quote("It is during our darkest moments that we must focus to see the light.","Aristotle"),
        new quote("Through discipline comes freedom.","Aristotle"),
        new quote("The way to get started is to quit talking and begin doing.","Walt Disney"),
        new quote("Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma – which is living with the results of other people's thinking.","Steve Jobs"),
        new quote("When you reach the end of your rope, tie a knot in it and hang on.   ","Franklin D. Roosevelt"),
        new quote("Tell me and I forget. Teach me and I remember. Involve me and I learn.","Benjamin Franklin"),
        new quote("I am not afraid of an army of lions led by a sheep; I am afraid of an army of sheep led by a lion.","Alexander the Great"),
        new quote("I have no special talent. I am only passionately curious.","Albert Einstein"),
        new quote("History Doesn't Repeat Itself, but It Often Rhymes","Mark Twain"),
        new quote("Here's lookin' at you kid.", 'Rick Blaine'),
        new quote("The future belongs to those who prepare for it today.","Malcolm X"),
        new quote("The successful warrior is the average man, with laser-like focus.", "Bruce Lee"),
        new quote("Don’t count the days, make the days count.", "Muhammad Ali"),
        new quote('The journey of a thousand miles begins with one step.', 'Lao Tzu'),
        new quote('You only live once, but if you do it right, once is enough.', 'Mae West'),
        new quote('You have power over your mind – not outside events. Realize this, and you will find strength.', 'Marcus Aurelius'),
        new quote('One drop of truth can outweigh an ocean of lies', 'Aleksandr Solzhenitsyn'),
        new quote("All that we see or seem is but a dream within a dream.", 'Edgar Allan Poe'),
        new quote('The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.', 'Marcel Proust'),
        new quote("If I cannot move heaven, I will raise hell.", "Virgil"),
        new quote("Fortune favors the bold.", "Virgil"),
        new quote("The eyes of others our prisons; their thoughts our cages.", "Virginia Woolf"),
        new quote("Nothing thicker than a knife's blade separates happiness from melancholy", "Virginia Woolf"),
        new quote("Everyone thinks of changing the world, but no one thinks of changing himself.", "Leo Tolstoy"),
        new quote("Everything comes in time to him who knows how to wait.", "Leo Tolstoy"),
        new quote("Wrong does not cease to be wrong because the majority share in it.", "Leo Tolstoy"),
        new quote("Boredom: the desire for desires.", "Leo Tolstoy"),
        new quote("I'm not bad, I'm just drawn that way.", "Jessica Rabbit"),
        new quote("Man cannot possess anything as long as he fears death.", "Leo Tolstoy"),
        new quote("If there was no suffering, man would not know his limits, would not know himself.", "Leo Tolstoy"),
        new quote("Life seems but a quick succession of busy nothings.", "Jane Austen"),
        new quote("The distance is nothing when one has a motive.", "Jane Austen"),
        new quote("Know your own happiness.", "Jane Austen"),
        new quote("Be the change that you wish to see in the world.", "Mahatma Gandhi"),
        new quote("A day without laughter is a day wasted.", "Nicolas Chamfort"),
        new quote("Never let your sense of morals prevent you from doing what is right.", "Isaac Asimov"),
        new quote("Without deviation from the norm, progress is not possible.", "Frank Zappa"),
        new quote("Do not fear to be eccentric in opinion, for every opinion now accepted was once eccentric.", "Bertrand Russell"),
        new quote("The first duty of a man is to think for himself", "Jose Marti"),
        new quote("I am the master of my fate, I am the captain of my soul.", "William Ernest Henley"),
        new quote("The philosophers have only interpreted the world, in various ways. The point, however, is to change it.", "Karl Marx"),
        new quote("I would never die for my beliefs because I might be wrong.", "Bertrand Russel"),
        new quote("The flame that burns Twice as bright burns half as long.", "Lao Tzu"),
        new quote("Life's battles don't always go to the stronger or faster man; But soon or late the man who wins is the man who thinks he can.", "Walter D. Wintle"),
        new quote("If you are going to try, go all the way, otherwise don't even start.", "Charles Bukowski"),
        new quote("Two roads diverged in a wood, and I - I took the one less traveled by, and that has made all the difference.", "Robert Frost"),
        new quote("And I hold within my hand the grains of the golden sand - How few! Yet how they creep through my fingers to the deep", "Edgar Allan Poe"),
        new quote("To be enthroned is to be enslaved and to be understood is to be leveled down and to be grasped is to reach one's fullness and like a ripe fruit to fall and be consumed.", "Khalil Gibran"),
        new quote("Know thy self, know thy enemies. A thousand battles, a thousand victories.", "Sun Tzu"),
        new quote("In the midst of chaos, there is also opportunity.", "Sun Tzu"),
        new quote("I am a cage, in search of a bird.", "Franz Kafka"),
        new quote("I think; therefore I am.", "Rene Descartes"),
        new quote("I'm gonna make him an offer he can't refuse.", "Vito Corleone"),
        new quote("I'm not gay, so I don't know much about Broadway musicals.", "Norm Macdonald"),
        new quote("Conquer yourself rather than the world.", "Rene Descartes"),
        new quote("Doubt is the origin of wisdom", "Rene Descartes"),
        new quote("It is not enough to have a good mind. The main thing is to use it well.", "Rene Descartes"),
        new quote("Dare to know! Have the courage to use your own intelligence!", "Immanuel Kant"),
        new quote("Tis better to have loved and lost than never to have loved at all", "Alfred Tennyson"),
        new quote("Water, water, everywhere, nor any drop to drink", "Samuel Taylor Coleridge"),
        new quote("The breaking of a wave cannot explain the whole sea.", "Vladimir Nabokov"),
        new quote("Curiosity is insubordination in its purest form.", "Vladimir Nabokov"),
        new quote("A writer should have the precision of a poet and the imagination of a scientist.", "Vladimir Nabokov"),
        new quote("I have loved the stars too fondly to be fearful of the night.", "Sarah Williams"),
        new quote("I shut my eyes and all the world drops dead; I lift my eyes and all is born again.", "Sylvia Plath"),
        new quote("Only those who will risk going too far can possibly find out how far one can go.", "T.S. Eliot"),
        new quote("This is the way the world ends. Not with a bang but a whimper.", "T.S. Eliot"),
        new quote("You only live twice: Once when you are born And once when you look death in the face", "Ian Fleming"),
        new quote("Be yourself; everyone else is already taken.", "Oscar Wilde"),
        new quote("In three words I can sum up everything I've learned about life: it goes on.", "Robert Frost"),
        new quote("Always forgive your enemies; nothing annoys them so much.", "Oscar Wilde"),
        new quote("It is better to be hated for what you are than to be loved for what you are not.", "Andre Gide"),
        new quote("A day without sunshine is like, you know, night.", "Steve Martin"),
        new quote("It is never too late to be what you might have been.", "George Eliot"),
        new quote("Logic will get you from A to Z; imagination will get you everywhere.", "Albert Einstein"),
        new quote("Folks are usually about as happy as they make their minds up to be.", "Abraham Lincoln"),
        new quote("The difference between genius and stupidity is: genius has its limits.", "Alexandre Dumas"),
        new quote("Not all those who wander are lost.", "J.R.R. Tolkien"),
        new quote("Things change. And friends leave. Life doesn't stop for anybody.", "Stephen Chbosky"),
        new quote("The only way out of the labyrinth of suffering is to forgive.", "John Green"),
        new quote("You never really understand a person until you consider things from his point of view... Until you climb inside of his skin and walk around in it.", "Harper Lee"),
        new quote("What a slut time is. She screws everybody.", "John Green"),
        new quote("But better to get hurt by the truth than comforted with a lie.", "Khaled Hosseini"),
        new quote("The truth is rarely pure and never simple.", "Oscar Wilde"),
        new quote("Perhaps one did not want to be loved so much as to be understood.", "George Orwell"),
        new quote("The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.", "Isaac Asimov"),
        new quote("Give a man a fire and he's warm for a day, but set fire to him and he's warm for the rest of his life.", "Terry Pratchett"),
        new quote("It's only those who do nothing that make no mistakes, I suppose.", "Joseph Conrad"),
        new quote("We live as we dream--alone. While the dream disappears, the life continues painfully.", "Joseph Conrad"),
        new quote("I don't like work--no man does--but I like what is in the work--the chance to find yourself. Your own reality--for yourself not for others--what no other man can ever know. They can only see the mere show, and never can tell what it really means.", "Joseph Conrad"),
        new quote("Your strength is just an accident arising from the weakness of others.", "Joseph Conrad"),
        new quote("Facing it, always facing it, that’s the way to get through. Face it.", "Joseph Conrad"),
        new quote("We can never cease to be ourselves.", "Joseph Conrad"),
        new quote("Nothing is impossible, the word itself says 'I'm possible'!", "Audrey Hepburn"),
        new quote("This life’s hard, but it’s harder if you’re stupid.", "George V. Higgins"),
        new quote("Count your age by friends, not years. Count your life by smiles, not tears.", "John Lennon"),
        new quote("Peace begins with a smile", "Mother Teresa"),
        new quote("To infinity and beyond", "Buzz Lightyear"),
        new quote("Frankly my dear, I don't give a damn.", "Rhett Butler"),
        new quote("Facts do not cease to exist because they are ignored.", "Aldous Huxley"),
        new quote("Those who believe in telekinetics, raise my hand.", "Kurt Vonnegut"),
        new quote("A good friend will always stab you in the front.", "Oscar Wilde"),
        new quote("Strike against war, for without you no battles can be fought.","Helen Keller"),
        new quote("Optimism is the faith that leads to achievement; nothing can be done without hope.","Helen Keller"),
        new quote("Imaginary evil is romantic and varied; real evil is gloomy, monotonous, barren, boring. Imaginary good is boring; real good is always new, marvelous, intoxicating.","Simone Weil"),
        new quote("It is not only in literature that fiction generates immorality. It does it also in life itself. For the substance of our life is almost exclusively composed of fiction","Simone Weil"),
        new quote("There is a level of cowardice lower than that of the conformist: the fashionable non-conformist.","Ayn Rand"),
        new quote("Human beings are born with different capacities. If they are free, they are not equal. And if they are equal, they are not free.", "Aleksandr Solzhenitsyn"),
        new quote("Nothing is more difficult, and therefore more precious, than to be able to decide.", "Napoleon Bonaparte"),
        new quote("I'm not afraid of death; I just don't want to be there when it happens.", "Woody Allen"),
        new quote("The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.", "Mark Twain"),
        new quote("Older men declare war. But it is youth that must fight and die.", "Herbert Hoover"),
        new quote("Life is pleasant. Death is peaceful. It's the transition that's troublesome.", "Isaac Asimov"),
        new quote("Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.", "Bill Keane"),
        new quote("You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one.", "John Lennon"),
        new quote("There is neither happiness nor misery in the world; there is only the comparison of one state with another, nothing more.", "Alexandre Dumas"),
        new quote("You cannot swim for new horizons until you have courage to lose sight of the shore.", "William Faulkner"),
        new quote("Blessed is he who expects nothing, for he shall never be disappointed.", "Alexander Pope"),
        new quote("You can cut all the flowers but you cannot keep Spring from coming.", "Pablo Neruda"),
        new quote("I don't think of all the misery, but of the beauty that still remains.", "Anne Frank"),
        new quote("This is where it all begins. Everything starts here, today.", "David Nicholls"),
        new quote("My life is a perfect graveyard of buried hopes.", "L.M. Montgomery"),
        new quote("Hope is a good breakfast, but it is a bad supper.", "Francis Bacon"),
        new quote("Shoot for the moon, even if you fail, you'll land among the stars", "Cecelia Ahern"),
        new quote("Remember, Hope is a good thing, maybe the best of things, and no good thing ever dies.", "Stephen King"),
        new quote("To err is human, to forgive, divine.", "Alexander Pope"),
        new quote("Fools rush in where angels fear to tread.", "Alexander Pope"),
        new quote("Charms strike the sight, but merit wins the soul.", "Alexander Pope"),
        new quote("Hold fast to dreams, For if dreams die life is a broken-winged bird, that cannot fly.", "Langston Hughes"),
        new quote("Any fool can know. The point is to understand.", "Albert Einstein"),
        new quote("Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", "Rumi"),
        new quote("God will not look you over for medals, degrees or diplomas but for scars.", "Elbert Hubbard"),
        new quote("Life would be tragic if it weren't funny.", "Stephen Hawking"),
        new quote("Risks must be taken because the greatest hazard in life is to risk nothing.", "Leo F. Buscaglia"),
        new quote("Honesty is the first chapter of the book wisdom.", "Thomas Jefferson"),
        new quote("Suffering is a gift. In it is hidden mercy.", "Rumi"),
        new quote("The question is not what you look at, but what you see.", "Henry David Thoreau"),
        new quote("It is better to fail in originality than to succeed in imitation.", "Herman Melville"),
        new quote("Failure is the condiment that gives success its flavor.", "Truman Capote"),
        new quote("Sometimes it takes a good fall to really know where you stand.", "Hayley Williams"),
        new quote("It is hard to fail, but it is worse never to have tried to succeed.", "Theodore Roosevelt"),
        new quote("Success is most often achieved by those who don't know that failure is inevitable.", "Coco Chanel"),
        new quote("Only those who dare to fail greatly can ever achieve greatly.", "Robert F. Kennedy"),
        new quote("In order to succeed, your desire for success should be greater than your fear of failure.", "Bill Cosby"),
        new quote("Success does not consist in never making mistakes but in never making the same one a second time.", "George Bernard Shaw"),
        new quote("You’re not obligated to win. You’re obligated to keep trying. To the best you can do everyday.", "Jason Mraz"),
        new quote("Success is a state of mind. If you want success, start thinking of yourself as a success.", "Joyce Brothers"),
        new quote("Find a purpose to serve, not a lifestyle to live.", "Criss Jami"),
        new quote("To be successful you need friends and to be very successful you need enemies.", "Sidney Sheldon"),
        new quote("Everything can be taken from a man but one thing: the last of the human freedoms—to choose one’s attitude in any given set of circumstances, to choose one’s own way.", "Viktor Frankl"),
        new quote("The only way of discovering the limits of the possible is to venture a little way past them into the impossible.", "Arthur C. Clarke"),
        new quote("It's not the load that breaks you down, it's the way you carry it.", "Lou Holtz"),
        new quote("When we are no longer able to change a situation, we are challenged to change ourselves.", "Viktor Frankl"),
        new quote("Do you want to know who you are? Don't ask. Act! Action will delineate and define you.", "Thomas Jefferson"),
        new quote("Nothing in the world is ever completely wrong. Even a stopped clock is right twice a day.", "Paulo Coelho"),
        new quote("All you need is love. But a little chocolate now and then doesn't hurt.", "Charles M. Schulz"),
        new quote("It’s no use going back to yesterday, because I was a different person then.", "Lewis Carroll"),
        new quote("Two wrongs don't make a right, but they make a good excuse.", "Thomas Szasz"),
        new quote("Substitute 'damn' every time you're inclined to write 'very;' your editor will delete it and the writing will be just as it should be.", "Mark Twain"),
        new quote("I like work: it fascinates me. I can sit and look at it for hours.", "Jerome K. Jerome"),
        new quote("I did not attend his funeral, but I sent a nice letter saying I approved of it.", "Mark Twain"),
        new quote("People say nothing is impossible, but I do nothing every day.", "A.A. Milne"),
        new quote("Time is a drug. Too much of it kills you.", "Terry Pratchett"),
        new quote("Even if you are on the right track, you’ll get run over if you just sit there.", "Will Rogers"),
        new quote("Never miss a good chance to shut up.", "Will Rogers"),
        new quote("Too many people spend money they haven't earned, to buy things they don't want, to impress people that they don't like.", "Will Rogers"),
        new quote("There are three kinds of men. The ones that learn by readin’. The few who learn by observation. The rest of them have to pee on the electric fence for themselves.", "Will Rogers"),
        new quote("Everything is funny as long as it is happening to somebody else.", "Will Rogers"),
        new quote("Rumor travels faster, but it don't stay put as long as truth.", "Will Rogers"),
        new quote("The road to success is dotted with many tempting parking spaces.", "Will Rogers"),
        new quote("Don't let yesterday take up too much of today", "Will Rogers"),
        new quote("Common sense ain't common.", "Will Rogers"),
        new quote("Everyone is ignorant, only on different subjects.", "Will Rogers"),
        new quote("When I die, I want to die like my grandfather who died peacefully in his sleep. Not screaming like all the passengers in his car.", "Will Rogers"),
        new quote("If pro is the opposite of con, what is the opposite of Congress?", "Will Rogers"),
        new quote("Good judgment comes from experience, and a lot of that comes from bad judgment.", "Will Rogers"),
        new quote("Talent is a wonderful thing, but it won't carry a quitter.", "Stephen King"),
        new quote("Difficulties vanish when faced boldly.", "Isaac Asimov"),
        new quote("Go as far as you can see and you will see further.", "Zig Ziglar"),
        new quote("Everyone has the fire, but the champions know when to ignite the spark.", "Amit Ray"),
        new quote("Motivation is when your dreams put on work clothes.", "Benjamin Franklin"),
        new quote("I drink your milkshake!", "Daniel Plainview"),
        new quote("Motivation gets you going and habit gets you there.", "Zig Ziglar"),
        new quote("The heights charm us, but the steps do not; with the mountain in our view we love to walk the plains.", "Johann Wolfgang von Goethe"),
        new quote("Tis in ourselves that we are thus or thus. Our bodies are our gardens to the which our wills are gardeners.", "William Shakespeare"),
        new quote("Where there is life, there is hope.", "Alyson Noel"),
        new quote("Act as if it was, and it will be.", "Lailah Gifty Akita"),
        new quote("To think is easy. To act is hard. But the hardest thing in the world is to act in accordance with your thinking.", "Johann Wolfgang von Goethe"),
        new quote("None are more hopelessly enslaved than those who falsely believe they are free.", "Johann Wolfgang von Goethe"),
        new quote("By seeking and blundering we learn.", "Johann Wolfgang von Goethe"),
        new quote("Knowing is not enough, we must apply. Willing is not enough, we must do", "Johann Wolfgang von Goethe"),
        new quote("A wise man will make more opportunities than he finds.", "Francis Bacon"),
        new quote("Money is a great servant but a bad master.", "Francis Bacon"),
        new quote("In order for the light to shine so brightly, the darkness must be present.", "Francis Bacon"),
        new quote("The less people speak of their greatness, the more we think of it.", "Francis Bacon"),
        new quote("A prudent question is one-half of wisdom.", "Francis Bacon"),
        new quote("Gentlemen, you can't fight in here! This is the war room!", "President Merkin Muffley"),
        new quote("The greatest lesson in life is to know that even fools are right sometimes.", "Winston Churchill"),
        new quote("The greater the artist, the greater the doubt. Perfect confidence is granted to the less talented as a consolation prize.", "Robert Hughes"),
        new quote("In the course of my life, I have often had to eat my words, and I must confess that I have always found it a wholesome diet.", "Winston Churchill"),
        new quote("A man should never be ashamed to own that he has been in the wrong, which is but saying in other words that he is wiser today than he was yesterday.", "Alexander Pope"),
        new quote("True humility does not know that it is humble. If it did, it would be proud from the contemplation of so fine a virtue.", "Martin Luther"),
        new quote("There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.", "Ernest Hemingway"),
        new quote("True humility is not thinking less of yourself; it is thinking of yourself less.", "Rick Warren"),
        new quote("On the highest throne in the world, we still sit only on our own bottom.", "Michel de Montaigne"),
        new quote("A great man is always willing to be little.", "Ralph Waldo Emerson"),        
        new quote("Every one is worthy of love, except him who thinks that he is.", "Oscar Wilde"),
        new quote("Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.", "Marcus Aurelius"),
        new quote("You either walk inside your story and own it or you stand outside your story and hustle for your worthiness.", "Brene Brown"),
        new quote("Not one of us can rest, be happy, be at home, be at peace with ourselves, until we end hatred and division.", "John Lewis"),
        new quote("The problem of Russia is not that it can't feed the poor, but that the rich never get full.", "Mikhail Zadornov"),
        new quote("Life isn't a matter of milestones but of moments.", "Rose Kennedy"),
        new quote("The man who moves a mountain begins by carrying away small stones.", "Confucius"),
        new quote("I can bear any pain as long as it has meaning.", "Haruki Murakami"),
        new quote("Disagreeing with deeply held beliefs is not hate.", "Unknown"),
        new quote("A state of war only serves as an excuse for domestic tyranny.", "Aleksandr Solzhenitsyn"),
        new quote("People sleep peaceably in their beds at night only because rough men stand ready to do violence on their behalf.", "George Orwell"),
        new quote("I have not failed. I've just found 10,000 ways that won't work.", "Thomas Edison"),
        new quote("A book read by a thousand different people is a thousand different books.", "Andrei Tarkovsky"),
        new quote("It is always darkest just before the dawn.", "Thomas Fuller"),
        new quote("Anyone can say they care, but watch their actions, not their words.", "Buddha"),
        new quote("War makes thieves and peace hangs them.", "George Herbert"),
        new quote("Change your opinions, keep to your principles; change your leaves, keep intact your roots.", "Victor Hugoo"),
        new quote("Even the darkest night will end and the sun will rise.", "Viktor Hugo"),
        new quote("To die is nothing, but it is terrible not to live.", "Viktor Hugo"),
        new quote("Life is the flower for which love is the honey.", "Viktor Hugo"),
        new quote("At the end of life death is a departure; but at life's beginning a departure is death.", "Viktor Hugo"),
        new quote("The future has several names. For the weak, it is impossible; for the faint-hearted, it is unknown; but for the valiant, it is ideal.", "Viktor Hugo"),
        new quote("There is nothing more powerful than an idea whose time has come.", "Viktor Hugo"),
        new quote("He who opens a school door closes a prison.", "Viktor Hugo"),
        new quote("To put everything in balance is good; to put everything in harmony is better.", "Viktor Hugo"),
        new quote("The wise man does not grow old, but ripens.", "Viktor Hugo"),
        new quote("Caution is the eldest child of wisdom.", "Viktor Hugo"),
        new quote("Adversity makes men and prosperity makes monsters.", "Viktor Hugo"),
        new quote("No fear, no regrets.", "Viktor Hugo"),
        new quote("Virtue has a veil, vice a mask", "Viktor Hugo"),
        new quote("Where the telescope ends the microscope begins, and who can say which has the wider vision?", "Viktor Hugo"),
        new quote("Concision in style, precision in thought, the decision in life.", "Viktor Hugo"),
        new quote("Everybody said, 'Follow your heart'. I did, it got broken", "Agatha Christie"),
        new quote("One of the saddest things in life, is the things one remembers.","Agatha Christie"),
        new quote("In the midst of life, we are in death.","Agatha Christie"),
        new quote("All is not lost, the unconquerable will, and study of revenge, immortal hate, and the courage never to submit or yield.","John Milton"),
        new quote("Long is the way and hard, that out of Hell leads up to light.","John Milton"),
        new quote("The brain is the single body part that named itself.","Unknown"),
        new quote("Most men die at 27, we just bury them at 72.","G.E. Marchand"),
        new quote("All in the valley of Death; Rode the six hundred.","Alfred Tennyson"),
        new quote("You can beat 40 scholars with one fact, but you can’t beat one idiot with 40 facts.","Mevlana"),
        new quote("Death must be so beautiful. To lie in the soft brown earth, with the grasses waving above one’s head, and listen to silence. To have no yesterday, and no tomorrow. To forget time, to forgive life, to be at peace.","Oscar Wilde"),
        new quote("Dude, suckin’ at something is the first step to being sorta good at something.","Jake The Dog"),
        new quote("Be a good person, but don’t waste time proving it","Manas Disoriya"),
        new quote("Do not correct a fool, or he will hate you; correct a wise man, and he will appreciate you.","Unknown"),
        new quote("You can avoid reality, but you can’t avoid the consequences of avoiding reality.","Ayn Rand"),
        new quote("The young man knows the rules, but the old man knows the exceptions.","Oliver Wendell Holmes"),
        new quote("Anyone who stops learning is old, whether at twenty or eighty.","Henry Ford"),
        new quote("The measure of a man is what he does with power.","Plato"),
        new quote("If we don't believe in freedom of expression for people we despise, we don't believe in it at all.","Noam Chomsky"),
        new quote("The most important conversations you’ll ever have are the ones you’ll have with yourself.","David Goggins"),
        new quote("Tension is who you think you should be. Relaxation is who you are.","Chinese Proverb"),
        new quote("True peace is not merely the absence of war, it is the presence of justice.","Jane Addams"),
        new quote("They say that time heals a broken heart. But time has stood still, since we’ve been apart.","Ray Charles"),
        new quote("If I had nine hours to chop down a tree, I’d spend the first six sharpening my axe","Abraham Lincoln"),
        new quote("No dark fate determines the future. We do.","Dalai Lama"),
        new quote("You know, with Hitler, the more I learn about that guy, the more I don’t care for him.","Norm Macdonald"),
        new quote("The ability to speak does not make you intelligent.","Qui-Gon Jinn"),
        new quote("Raise your words, not voice. It is rain that grows flowers, not thunder.","Unknown"),
        new quote("Whoever fights monsters should see to it that in the process he does not become a monster. And if you gaze long enough into an abyss, the abyss will gaze back into you.","Friedrich Nietzsche"),
        new quote("Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"),
        new quote("Most people work just hard enough not to get fired and get paid just enough money not to quit.","George Carlin"),
        new quote("Time is too slow for those who wait, too swift for those who fear, too long for those who grieve, too short for those who rejoice, but for those who love, time is eternity.","Henry Van Dyke"),
        new quote("Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.","Marcus Aurelius"),
        new quote("A little nonsense now and then, is cherished by the wisest men.","Roald Dahl"),
        new quote("Such is life","Ned Kelly"),
        new quote("To play a wrong note is insignificant; to play without passion is inexcusable.","Ludwig van Beethoven"),
        new quote("All the world’s a stage, and all the men and women merely players","William Shakespeare"),
        new quote("Never test another man by your own weakness.", "Joseph Conrad")
        //new quote("",""),
    ]       
   
}


//returns quote_list to motivational_quote
export function Return_quote_list(index) {
    return quotes_list[index];
}

//Returns list length
export function Return_quote_list_length() {
    return quotes_list.length;
}
