//This js file contains the quotes

let quotes_list = [];

//quote object constructor
function quote(quote_input, author) {
    this.the_quote = quote_input;
    this.quote_author = author;
}

export function Quote_list_initialisation() {
    //Quote database
    quotes_list = [        
    new quote("The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.", "Isaac Asimov"),
    new quote("Only those who dare to fail greatly can ever achieve greatly.", "Robert F. Kennedy"),
    new quote("No fear, no regrets.", "Victor Hugo"),
    new quote('If you want to fly, you have to give up what weighs you down.','Roy T. Bennett'),
    new quote('Some are born great, others achieve greatness.','William Shakespeare'),
    new quote('Life is not a problem to be solved, but a reality to be experienced.','Soren Kierkegaard'),
    new quote('Hope is the confusion of the desire for a thing with its probability.','Arthur Schopenhauer'),
    new quote("Talent is a wonderful thing, but it won't carry a quitter.", "Stephen King"),
    new quote("Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma – which is living with the results of other people's thinking.","Steve Jobs"),
    new quote("Everything comes in time to him who knows how to wait.", "Leo Tolstoy"),
    new quote("You're not obligated to win. You're obligated to keep trying. To the best you can do everyday.", "Jason Mraz"),
    new quote("Optimism is the faith that leads to achievement; nothing can be done without hope.","Helen Keller"),
    new quote("Man cannot possess anything as long as he fears death.", "Leo Tolstoy"),
    new quote("There is neither happiness nor misery in the world; there is only the comparison of one state with another, nothing more.", "Alexandre Dumas"),
    new quote("We can never cease to be ourselves.", "Joseph Conrad"),
    new quote('The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.', 'Marcel Proust'),
    new quote("Life is the flower for which love is the honey.", "Victor Hugo"),
    new quote("Trees are poems the earth writes upon the sky, We fell them down and turn them into paper, so that we may record our emptiness.","Khalil Gibran"),
    new quote("Gentlemen, you can't fight in here! This is the war room!", "President Merkin Muffley"),
    new quote("Those who have a 'why' to live, can bear with almost any 'how'.",'Victor Frankl'),
    new quote("A great man is always willing to be little.", "Ralph Waldo Emerson"),        
    new quote("The young man knows the rules, but the old man knows the exceptions.","Oliver Wendell Holmes Jr."),
    new quote("The only way out of the labyrinth of suffering is to forgive.", "John Green"),
    new quote("No great mind has ever existed without a touch of madness.","Aristotle"),
    new quote("True peace is not merely the absence of war, it is the presence of justice.","Jane Addams"),
    new quote("You either walk inside your story and own it or you stand outside your story and hustle for your worthiness.", "Brene Brown"),
    new quote("Anyone can say they care, but watch their actions, not their words.", "Buddha"),
    new quote("None are more hopelessly enslaved than those who falsely believe they are free.", "Johann Wolfgang von Goethe"),
    new quote("True humility does not know that it is humble. If it did, it would be proud from the contemplation of so fine a virtue.", "Martin Luther"),
    new quote('The battleline between good and evil runs through the heart of every man.','Aleksandr Solzhenitsyn'),
    new quote("Do, or do not. There is no 'try'","Yoda"),
    new quote('That which does not kill us makes us stronger.','Friedrich Nietzsche'),
    new quote("Educating the mind without educating the heart is no education at all.","Aristotle"),
    new quote("It is never too late to be what you might have been.", "George Eliot"),
    new quote("Everyone thinks of changing the world, but no one thinks of changing himself.", "Leo Tolstoy"),
    new quote('The fool doth think he is wise, but the wise man knows himself to be a fool','William Shakespeare'),
    new quote("A friend to all is a friend to none.","Aristotle"),     
    new quote("Disagreeing with deeply held beliefs is not hate.", "Unknown"),
    new quote("True humility is not thinking less of yourself; it is thinking of yourself less.", "Rick Warren"),
    new quote("The purpose of education is to replace an empty mind with an open one.","Malcolm Forbes"),
    new quote("This is where it all begins. Everything starts here, today.", "David Nicholls"),
    new quote("Where there is life, there is hope.", "Alyson Noel"),
    new quote("Human beings are born with different capacities. If they are free, they are not equal. And if they are equal, they are not free.", "Aleksandr Solzhenitsyn"),
    new quote("Wrong does not cease to be wrong because the majority share in it.", "Leo Tolstoy"),
    new quote("The less people speak of their greatness, the more we think of it.", "Francis Bacon"),
    new quote("If pro is the opposite of con, what is the opposite of Congress?", "Will Rogers"),
    new quote("Never test another man by your own weakness.", "Joseph Conrad"),
    new quote("It is better to fail in originality than to succeed in imitation.", "Herman Melville"),
    new quote("Nothing is impossible, the word itself says 'I'm possible'!", "Audrey Hepburn"),
    new quote("In three words I can sum up everything I've learned about life: it goes on.", "Robert Frost"),
    new quote("A wise man will make more opportunities than he finds.", "Francis Bacon"),
    new quote("The hero and the coward both feel the same thing. But the hero uses his fear, projects it onto his opponent, while the coward runs. It's the same thing, fear, but it's what you do with it that matters.","Cus D'amato"),
    new quote("All is not lost, the unconquerable will, and study of revenge, immortal hate, and the courage never to submit or yield.","John Milton"),
    new quote("It ain't about how hard you can hit. It's about how hard you can get hit and keep moving forward.","Rocky Balboa"),
    new quote("Suffering is a gift. In it is hidden mercy.", "Rumi"),
    new quote("Fear? What has a man to do with fear? Chance rules our lives, and the future is all unknown. Best live as we may, from day to day.","Sophocles"),
    new quote("War makes thieves and peace hangs them.", "George Herbert"),
    new quote("Tis better to have loved and lost than never to have loved at all", "Alfred Tennyson"),
    new quote("Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"),
    new quote("Life is too deep for words, so don't try to describe it, just live it.","C. S. Lewis"),
    new quote("To go wrong in one's own way is better than to go right in someone else's.",'Fyodor Dostoevsky'),
    new quote("Be the change that you wish to see in the world.", "Mahatma Gandhi"),
    new quote("But better to get hurt by the truth than comforted with a lie.", "Khaled Hosseini"),
    new quote("A man, though wise, should never be ashamed of learning more, and must unbend his mind.","Sophocles"),
    new quote("Even if you are on the right track, you'll get run over if you just sit there.", "Will Rogers"),
    new quote("Honesty is the first chapter of the book wisdom.", "Thomas Jefferson"),
    new quote("This above all: to thine own self be true.", "William Shakespeare"),
    new quote("Happiness is a butterfly, which when pursued, is always just beyond your grasp, but which, if you will sit down quietly, may alight upon you.", "Nathaniel Hawthorne"),
    new quote('Great men are like eagles, and build their nest on some lofty solitude.','Arthur Schopenhauer'),
    new quote("You know, with Hitler, the more I learn about that guy, the more I don't care for him.","Norm Macdonald"),
    new quote("Everybody said, 'Follow your heart'. I did, it got broken", "Agatha Christie"),
    new quote('Hope in reality is the worst of all evils because it prolongs the torments of man.','Friedrich Nietzsche'),
    new quote('Attitude is a choice. Happiness is a choice. Optimism is a choice. Kindness is a choice. Giving is a choice. Respect is a choice. Whatever choice you make makes you. Choose wisely.','Roy T. Bennett'),
    new quote("Things change. And friends leave. Life doesn't stop for anybody.", "Stephen Chbosky"),
    new quote("The deeper that sorrow carves into your being, the more joy you can contain.","Khalil Gibran"),
    new quote("It is not only in literature that fiction generates immorality. It does it also in life itself. For the substance of our life is almost exclusively composed of fiction","Simone Weil"),
    new quote("This life's hard, but it's harder if you're stupid.", "George V. Higgins"),
    new quote("If there was no suffering, man would not know his limits, would not know himself.", "Leo Tolstoy"),
    new quote("Anyone who stops learning is old, whether at twenty or eighty.","Henry Ford"),
    new quote("Death must be so beautiful. To lie in the soft brown earth, with the grasses waving above one's head, and listen to silence. To have no yesterday, and no tomorrow. To forget time, to forgive life, to be at peace.","Oscar Wilde"),
    new quote("Never was anything great achieved without danger.","Niccolo Machiavelli"),
    new quote("My life is a perfect graveyard of buried hopes.", "L.M. Montgomery"),
    new quote("All the great utterances of man have to be judged not by the letter but by the spirit — the spirit which unfolds itself with the growth of life in history.", "Rabindranath Tagore"),
    new quote("Has it ever struck you that life is all memory, except for the one present moment that goes by you so quick you hardly catch it going?","Tennessee Williams"),
    new quote("Everything is funny as long as it is happening to somebody else.", "Will Rogers"),
    new quote("I'm thankful for women. I think they are more intelligent than men. Also, without women, there would be no cookies.","Norm Macdonald"),
    new quote('Most people do not really want freedom, because freedom involves responsibility, and most people are frightened of responsibility.','Sigmund Freud'),
    new quote("Without deviation from the norm, progress is not possible.", "Frank Zappa"),
    new quote("Raise your words, not voice. It is rain that grows flowers, not thunder.","Unknown"),
    new quote("The ability to speak does not make you intelligent.","Qui-Gon Jinn"),
    new quote("To be enthroned is to be enslaved and to be understood is to be leveled down and to be grasped is to reach one's fullness and like a ripe fruit to fall and be consumed.", "Khalil Gibran"),
    new quote("Folks are usually about as happy as they make their minds up to be.", "Abraham Lincoln"),
    new quote("Never let your sense of morals prevent you from doing what is right.", "Isaac Asimov"),
    new quote("I don't think of all the misery, but of the beauty that still remains.", "Anne Frank"),
    new quote("I have loved the stars too fondly to be fearful of the night.", "Sarah Williams"),
    new quote("Water, water, everywhere, nor any drop to drink", "Samuel Taylor Coleridge"),
    new quote("Some of you say, “Joy is greater than sorrow,” and others say, “Nay, sorrow is the greater.” But I say unto you, they are inseparable. Together they come, and when one sits alone with you at your board, remember that the other is asleep upon your bed.","Khalil Gibran"),
    new quote("There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.", "Ernest Hemingway"),
    new quote('Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.','Martin Luther King jr.'),
    new quote("Wholeness is not achieved by cutting off a portion of one's being, but by integration of the contraries.','Carl Gustav Jung"),
    new quote('There is only one thing that makes a dream impossible to achieve: the fear of failure.','Paulo Coelho'),
    new quote("Everything can be taken from a man but one thing: the last of the human freedoms—to choose one's attitude in any given set of circumstances, to choose one's own way.", "Victor Frankl"),
    new quote("I have no special talent. I am only passionately curious.","Albert Einstein"),
    new quote("What a slut time is. She screws everybody.", "John Green"),
    new quote('You can be sincere and still be stupid.','Fyodor Dostoevsky'),
    new quote("You can beat 40 scholars with one fact, but you can't beat one idiot with 40 facts.","Mevlana"),
    new quote('It takes something more than intelligence to act intelligently.','Fyodor Dostoevsky'),
    new quote("The greater the artist, the greater the doubt. Perfect confidence is granted to the less talented as a consolation prize.", "Robert Hughes"),
    new quote("The future has several names. For the weak, it is impossible; for the faint-hearted, it is unknown; but for the valiant, it is ideal.", "Victor Hugo"),
    new quote("Say 'ello to my little friend!", 'Tony Montana'),
    new quote("Out of suffering have emerged the strongest souls; the most massive characters are seared with scars.","Khalil Gibran"),
    new quote("Find a purpose to serve, not a lifestyle to live.", "Criss Jami"),
    new quote("When you find yourself in a hole, quit digging.","Will Rogers"),
    new quote("On the highest throne in the world, we still sit only on our own bottom.", "Michel de Montaigne"),
    new quote("The hardest thing to learn in life is which bridge to cross and which to burn.", "David Russell"),
    new quote("I think; therefore I am.", "Rene Descartes"),
    new quote("Facing it, always facing it, that's the way to get through. Face it.", "Joseph Conrad"),
    new quote("It is during our darkest moments that we must focus to see the light.","Aristotle"),
    new quote('It does not matter how slowly you go so long as you do not stop.','Confucius'),
    new quote("They say that time heals a broken heart. But time has stood still, since we've been apart.","Ray Charles"),
    new quote("It is hard to fail, but it is worse never to have tried to succeed.", "Theodore Roosevelt"),
    new quote("Motivation is when your dreams put on work clothes.", "Benjamin Franklin"),
    new quote('You have power over your mind – not outside events. Realize this, and you will find strength.', 'Marcus Aurelius'),
    new quote("Even the darkest night will end and the sun will rise.", "Victor Hugo"),
    new quote('What the superior man seeks is in himself; what the small man seeks is in others.','Confucius'),
    new quote("Act as if it was, and it will be.", "Lailah Gifty Akita"),
    new quote("If you let your head get too big, it'll break your neck.","Elvis Presley"),
    new quote("There are three kinds of men. The ones that learn by readin'. The few who learn by observation. The rest of them have to pee on the electric fence for themselves.", "Will Rogers"),
    new quote('The valor that struggles is better than the weakness that endures.','Georg Wilhelm Friedrich Hegel'),
    new quote("Be a good person, but don't waste time proving it","Manas Disoriya"),
    new quote("There's no coming to consciousness without pain.",'Carl Gustav Jung'),
    new quote("Nothing thicker than a knife's blade separates happiness from melancholy", "Virginia Woolf"),
    new quote("An eye for an eye, and the whole world would be blind.","Khalil Gibran"),
    new quote("Most people work just hard enough not to get fired and get paid just enough money not to quit.","George Carlin"),
    new quote("To judge a man by his weakest link or deed is like judging the power of the ocean by one wave.","Elvis Presley"),
    new quote("A man should never be ashamed to own that he has been in the wrong, which is but saying in other words that he is wiser today than he was yesterday.", "Alexander Pope"),
    new quote("I like work: it fascinates me. I can sit and look at it for hours.", "Jerome K. Jerome"),
    new quote('What is adequacy? Adequacy is no standard at all.','Winston Churchill'),
    new quote("Truth is like the sun. You can shut it out for a time, but it ain't going away.","Elvis Presley"),
    new quote("The question is not what you look at, but what you see.", "Henry David Thoreau"),
    new quote("A book read by a thousand different people is a thousand different books.", "Andrei Tarkovsky"),
    new quote("I'm not afraid of death; I just don't want to be there when it happens.", "Woody Allen"),
    new quote("The problem of Russia is not that it can't feed the poor, but that the rich never get full.", "Mikhail Zadornov"),
    new quote("Older men declare war. But it is youth that must fight and die.", "Herbert Hoover"),
    new quote("More than machinery, we need humanity. More than cleverness, we need kindness and gentleness. Without these qualities life will be violent and all will be lost.", "Charlie Chaplin"),
    new quote('Your pain is the breaking of the shell that encloses your understanding.','Khalil Gibran'),
    new quote("Success is most often achieved by those who don't know that failure is inevitable.", "Coco Chanel"),
    new quote("Tis in ourselves that we are thus or thus. Our bodies are our gardens to the which our wills are gardeners.", "William Shakespeare"),
    new quote("I did not attend his funeral, but I sent a nice letter saying I approved of it.", "Mark Twain"),
    new quote("I have not failed. I've just found 10,000 ways that won't work.", "Thomas Edison"),
    new quote('Mostly it is loss which teaches us about the worth of things.','Arthur Schopenhauer'),
    new quote("The wise man does not grow old, but ripens.", "Victor Hugo"),
    new quote("God will not look you over for medals, degrees or diplomas but for scars.", "Elbert Hubbard"),
    new quote("Virtue has a veil, vice a mask", "Victor Hugo"),
    new quote("A day without sunshine is like, you know, night.", "Steve Martin"),
    new quote("The only way of discovering the limits of the possible is to venture a little way past them into the impossible.", "Arthur C. Clarke"),
    new quote("Substitute 'damn' every time you're inclined to write 'very;' your editor will delete it and the writing will be just as it should be.", "Mark Twain"),
    new quote("It's only those who do nothing that make no mistakes, I suppose.", "Joseph Conrad"),
    new quote("Few men are born brave, many become so through training and force of discipline.","Vegetius"),
    new quote('The fault, dear Brutus, is not in our stars, but in ourselves.','William Shakespeare'),
    new quote('Talent hits a target no one else can hit. Genius hits a target no one else can see.','Arthur Schopenhauer'),
    new quote("If I cannot move heaven, I will raise hell.", "Virgil"),
    new quote("Wisdom outweighs any wealth.","Sophocles"),
    new quote("You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one.", "John Lennon"),
    new quote("The greatest lesson in life is to know that even fools are right sometimes.", "Winston Churchill"),
    new quote('Trust in dreams, for in them is hidden the gate to eternity.','Khalil Gibran'),
    new quote("All that glisters is not gold; often have you heard that told.","William Shakespeare"),
    new quote("Go as far as you can see and you will see further.", "Zig Ziglar"),
    new quote("Nothing in the world is ever completely wrong. Even a stopped clock is right twice a day.", "Paulo Coelho"),
    new quote("Count your age by friends, not years. Count your life by smiles, not tears.", "John Lennon"),
    new quote('The best books... are those that tell you what you know already.','George Orwell'),
    new quote("One of the saddest things in life, is the things one remembers.","Agatha Christie"),
    new quote("A writer should have the precision of a poet and the imagination of a scientist.", "Vladimir Nabokov"),
    new quote("The distance is nothing when one has a motive.", "Jane Austen"),
    new quote("Lies run sprints, but the truth runs marathons.","Michael Jackson"),
    new quote("Money is a great servant but a bad master.", "Francis Bacon"),
    new quote('We cannot change anything unless we accept it.','Carl Gustav Jung'),
    new quote("You only live twice: Once when you are born And once when you look death in the face", "Ian Fleming"),
    new quote("I would never die for my beliefs because I might be wrong.", "Bertrand Russel"),
    new quote('The privilege of a lifetime is to become who you truly are.','Carl Gustav Jung'),
    new quote('Nothing great in the world was accomplished without passion.','Georg Wilhelm Friedrich Hegel'),
    new quote("Dare to know! Have the courage to use your own intelligence!", "Immanuel Kant"),
    new quote("You are what you do, not what you say you'll do.",'Carl Gustav Jung'),
    new quote("I don't like to commit myself about Heaven and Hell, you see, I have friends in both places.","Mark Twain"),
    new quote("Nothing is more difficult, and therefore more precious, than to be able to decide.", "Napoleon Bonaparte"),
    new quote("I can bear any pain as long as it has meaning.", "Haruki Murakami"),
    new quote("History Doesn't Repeat Itself, but It Often Rhymes","Mark Twain"),
    new quote("Concision in style, precision in thought, the decision in life.", "Victor Hugo"),
    new quote("Too many people spend money they haven't earned, to buy things they don't want, to impress people that they don't like.", "Will Rogers"),
    new quote('You only live once, but if you do it right, once is enough.', 'Mae West'),
    new quote("Doubt is the origin of wisdom", "Rene Descartes"),
    new quote('The price of greatness is responsibility.','Winston Churchill'),
    new quote("You can cut all the flowers but you cannot keep Spring from coming.", "Pablo Neruda"),
    new quote("Wealth consists not in having great possessions, but in having few wants.","Epictetus"),
    new quote("Dude, suckin' at something is the first step to being sorta good at something.","Jake The Dog"),
    new quote('We seldom think of what we have, but always of what we lack.','Arthur Schopenhauer'),
    new quote("The man who moves a mountain begins by carrying away small stones.", "Confucius"),
    new quote("Life seems but a quick succession of busy nothings.", "Jane Austen"),
    new quote("Blessed is he who expects nothing, for he shall never be disappointed.", "Alexander Pope"),
    new quote('To improve is to change, so to be perfect is to change often.','Winston Churchill'),
    new quote("Life isn't a matter of milestones but of moments.", "Rose Kennedy"),
    new quote("And I hold within my hand the grains of the golden sand - How few! Yet how they creep through my fingers to the deep", "Edgar Allan Poe"),
    new quote("The breaking of a wave cannot explain the whole sea.", "Vladimir Nabokov"),
    new quote("Success is a state of mind. If you want success, start thinking of yourself as a success.", "Joyce Brothers"),
    new quote("I shut my eyes and all the world drops dead; I lift my eyes and all is born again.", "Sylvia Plath"),
    new quote("The brain is the single body part that named itself.","Unknown"),
    new quote("Knowing is not enough, we must apply. Willing is not enough, we must do", "Johann Wolfgang von Goethe"),
    new quote("Only those who will risk going too far can possibly find out how far one can go.", "T.S. Eliot"),
    new quote("Change your opinions, keep to your principles; change your leaves, keep intact your roots.", "Victor Hugoo"),
    new quote("Everyone has the fire, but the champions know when to ignite the spark.", "Amit Ray"),
    new quote("A state of war only serves as an excuse for domestic tyranny.", "Aleksandr Solzhenitsyn"),
    new quote("Such is life.","Ned Kelly"),
    new quote("All the world's a stage, and all the men and women merely players","William Shakespeare"),
    new quote('Becoming a great leader does not mean being perfect. it means living with your imperfections.','Lolly Daskal'),
    new quote('A man can be himself only so long as he is alone; and if he does not love solitude, he will not love freedom; for it is only when he is alone that he is really free.','Arthur Schopenhauer'),
    new quote('Deep into that darkness peering, long I stood there, wondering, fearing, doubting, dreaming dreams no mortal ever dared to dream before.','Edgar Allan Poe'),
    new quote("It is not the mountain we conquer but ourselves.","Sir Edmund Hillary"),
    new quote("The most important conversations you'll ever have are the ones you'll have with yourself.","David Goggins"),
    new quote("The truth is rarely pure and never simple.", "Oscar Wilde"),
    new quote("He who has overcome his fears will truly be free.","Aristotle"),
    new quote('Who looks outside, dreams; who looks inside, awakes.','Carl Gustav Jung'),
    new quote('There are no beautiful surfaces without a terrible depth.','Friedrich Nietzsche'),
    new quote("Always forgive your enemies; nothing annoys them so much.", "Oscar Wilde"),
    new quote("When things go wrong, don't go with them.","Elvis Presley"),
    new quote("Difficulties vanish when faced boldly.", "Isaac Asimov"),
    new quote("Give a man a fire and he's warm for a day, but set fire to him and he's warm for the rest of his life.", "Terry Pratchett"),
    new quote("Any fool can know. The point is to understand.", "Albert Einstein"),
    new quote('Nothing in this world is harder than speaking the truth, nothing easier than flattery.','Fyodor Dostoevsky'),
    new quote("Through discipline comes freedom.","Aristotle"),
    new quote("If we don't believe in freedom of expression for people we despise, we don't believe in it at all.","Noam Chomsky"),
    new quote("Two roads diverged in a wood, and I - I took the one less traveled by, and that has made all the difference.", "Robert Frost"),
    new quote("Marry, and you will regret it; do not marry, you will also regret it; marry or don't marry, you will regret it either way.','Soren Kierkegaard"),
    new quote("It is nationalism which engenders nations, and not the other way round.","Ernest Gellner"),
    new quote("The man who views the world at 50 the same as he did at 20 has wasted 30 years of his life.","Muhammad Ali"),
    new quote("Charms strike the sight, but merit wins the soul.", "Alexander Pope"),
    new quote('Success is the ability to go from one failure to another with no loss of enthusiasm.','Winston Churchill'),
    new quote("A little nonsense now and then, is cherished by the wisest men.","Roald Dahl"),
    new quote("The smallest act of kindness is worth more than the greatest intention.","Khalil Gibran"),
    new quote("Hope is a good breakfast, but it is a bad supper.", "Francis Bacon"),
    new quote("In order for the light to shine so brightly, the darkness must be present.", "Francis Bacon"),
    new quote("Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.", "Marcus Aurelius"),
    new quote("To err is human, to forgive, divine.", "Alexander Pope"),
    new quote("Remember, Hope is a good thing, maybe the best of things, and no good thing ever dies.", "Stephen King"),
    new quote("To be successful you need friends and to be very successful you need enemies.", "Sidney Sheldon"),
    new quote("The difference between genius and stupidity is: genius has its limits.", "Alexandre Dumas"),
    new quote("Do not fear to be eccentric in opinion, for every opinion now accepted was once eccentric.", "Bertrand Russell"),
    new quote('Blessed are the merciful for they will be shown mercy.','Jesus Christ'),
    new quote('Who controls the past controls the future. Who controls the present controls the past.','George Orwell'),
    new quote("Failure is the condiment that gives success its flavor.", "Truman Capote"),
    new quote("Money, if it does not bring you happiness, will at least help you be miserable in comfort.","Helen Gurley Brown"),
    new quote("Tenderness and kindness are not signs of weakness and despair, but manifestations of strength and resolution.","Khalil Gibran"),
    new quote("Life is pleasant. Death is peaceful. It's the transition that's troublesome.", "Isaac Asimov"),
    new quote("There is a level of cowardice lower than that of the conformist: the fashionable non-conformist.","Ayn Rand"),
    new quote("Curiosity is insubordination in its purest form.", "Vladimir Nabokov"),
    new quote('Everything that irritates us about others can lead us to an understanding of ourselves.','Carl Gustav Jung'),
    new quote("Every one is worthy of love, except him who thinks that he is.", "Oscar Wilde"),
    new quote("Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.", "Bill Keane"),
    new quote('Ask and it will be given to you; seek and you will find; knock and the door will be opened to you. For everyone who asks receives; the one who seeks finds; and to the one who knocks, the door will be opened.','Jesus Christ'),
    new quote("When I die, I want to die like my grandfather who died peacefully in his sleep. Not screaming like all the passengers in his car.", "Will Rogers"),
    new quote("Patience is bitter, but its fruit is sweet.","Aristotle"),
    new quote('Mistakes are, after all, the foundations of truth, and if a man does not know what a thing is, it is at least an increase in knowledge if he knows what it is not. ','Carl Gustav Jung'),
    new quote('Our lives begin to end the day we become silent about things that matter.','Martin Luther King jr.'),
    new quote("The more you know, the more you know you don't know.","Aristotle"),
    new quote('The journey of a thousand miles begins with one step.', 'Lao Tzu'),
    new quote("People sleep peaceably in their beds at night only because rough men stand ready to do violence on their behalf.", "George Orwell"),
    new quote("All you need is love. But a little chocolate now and then doesn't hurt.", "Charles M. Schulz"),
    new quote("Those who believe in telekinetics, raise my hand.", "Kurt Vonnegut"),
    new quote("To think is easy. To act is hard. But the hardest thing in the world is to act in accordance with your thinking.", "Johann Wolfgang von Goethe"),
    new quote("Create with the heart; build with the mind.","Criss Jami"),
    new quote("By seeking and blundering we learn.", "Johann Wolfgang von Goethe"),
    new quote('Face the facts of being what you are, for that is what changes what you are.','Soren Kierkegaard'),
    new quote('Veni Vidi Vici','Julius Caesar'),
    new quote("A prudent question is one-half of wisdom.", "Francis Bacon"),
    new quote("To give someone a piece of your heart, is worth more than all the wealth in the world.","Michael Jackson"),
    new quote('Change alone is eternal, perpetual, immortal.','Arthur Schopenhauer'),
    new quote("The measure of a man is what he does with power.","Plato"),
    new quote("Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",'Roy T. Bennett'),
    new quote('Truth is found neither in the thesis nor the antithesis, but in an emergent synthesis which reconciles the two.','Georg Wilhelm Friedrich Hegel'),
    new quote("You have enemies? Good. That means you've stood up for something in your life.",'Winston Churchill'),
    new quote("Some mountains are higher than others, some roads steeper than the next. There are hardships and setbacks, but you can't let them stop you. ","Muhammad Ali"),
    new quote("Know thy self, know thy enemies. A thousand battles, a thousand victories.", "Sun Tzu"),
    new quote('The first half of life is devoted to forming a healthy ego, the second half is going inward and letting go of it.','Carl Gustav Jung'),
    new quote("In a world filled with hate, we must still dare to hope.","Michael Jackson"),
    new quote("When you reach the end of your rope, tie a knot in it and hang on.","Franklin D. Roosevelt"),
    new quote('Genuine tragedies in the world are not conflicts between right and wrong. They are conflicts between two rights','Georg Wilhelm Friedrich Hegel'),
    new quote("The philosophers have only interpreted the world, in various ways. The point, however, is to change it.", "Karl Marx"),
    new quote("You never really understand a person until you consider things from his point of view... Until you climb inside of his skin and walk around in it.", "Harper Lee"),
    new quote("Boredom: the desire for desires.", "Leo Tolstoy"),
    new quote("Generosity is giving more than you can, and pride is taking less than you need.","Khalil Gibran"),
    new quote("It is only with the heart that one can see rightly; what is essential is invisible to the eye.","Antoine de Saint-Exupery"),
    new quote("Do not correct a fool, or he will hate you; correct a wise man, and he will appreciate you.","Unknown"),
    new quote("The flame that burns Twice as bright burns half as long.", "Lao Tzu"),
    new quote("Everyone is ignorant, only on different subjects.", "Will Rogers"),
    new quote("In order to succeed, your desire for success should be greater than your fear of failure.", "Bill Cosby"),
    new quote("Bigotry tries to keep truth safe in its hand; With a grip that kills it.","Rabindranath Tagore"),
    new quote("Hold fast to dreams, For if dreams die life is a broken-winged bird, that cannot fly.", "Langston Hughes"),
    new quote("Sometimes it takes a good fall to really know where you stand.", "Hayley Williams"),
    new quote("Time is a drug. Too much of it kills you.", "Terry Pratchett"),
    new quote("Don't let yesterday take up too much of today", "Will Rogers"),
    new quote("Don't count the days, make the days count.", "Muhammad Ali"),
    new quote("To play a wrong note is insignificant; to play without passion is inexcusable.","Ludwig van Beethoven"),
    new quote("Desire is half of life; indifference is half of death.","Khalil Gibran"),
    new quote("A good friend will always stab you in the front.", "Oscar Wilde"),
    new quote("Whoever fights monsters should see to it that in the process he does not become a monster. And if you gaze long enough into an abyss, the abyss will gaze back into you.","Friedrich Nietzsche"),
    new quote("I am not afraid of an army of lions led by a sheep; I am afraid of an army of sheep led by a lion.","Alexander the Great"),
    new quote("Know your own happiness.", "Jane Austen"),
    new quote("Long is the way and hard, that out of Hell leads up to light.","John Milton"),
    new quote("Rumor travels faster, but it don't stay put as long as truth.", "Will Rogers"),
    new quote("Logic will get you from A to Z; imagination will get you everywhere.", "Albert Einstein"),
    new quote("At the end of life death is a departure; but at life's beginning a departure is death.", "Victor Hugo"),
    new quote("Strike against war, for without you no battles can be fought.","Helen Keller"),
    new quote("Good judgment comes from experience, and a lot of that comes from bad judgment.", "Will Rogers"),
    new quote("It is better to be hated for what you are than to be loved for what you are not.", "Andre Gide"),
    new quote("You cannot swim for new horizons until you have courage to lose sight of the shore.", "William Faulkner"),
    new quote("Caution is the eldest child of wisdom.", "Victor Hugo"),
    new quote("Success does not consist in never making mistakes but in never making the same one a second time.", "George Bernard Shaw"),
    new quote("The future belongs to those who prepare for it today.","Malcolm X"),
    new quote("To put everything in balance is good; to put everything in harmony is better.", "Victor Hugo"),
    new quote('One should use common words to say uncommon things','Arthur Schopenhauer'),
    new quote("The successful warrior is the average man, with laser-like focus.", "Bruce Lee"),
    new quote("I am a cage, in search of a bird.", "Franz Kafka"),
    new quote("If you are going to try, go all the way, otherwise don't even start.", "Charles Bukowski"),
    new quote("Knowing yourself is the beginning of all wisdom.","Aristotle"),
    new quote("We live as we dream--alone. While the dream disappears, the life continues painfully.", "Joseph Conrad"),
    new quote("Fortune favors the bold.", "Virgil"),
    new quote('We learn from history that we do not learn from history.','Georg Wilhelm Friedrich Hegel'),
    new quote("To die is nothing, but it is terrible not to live.", "Victor Hugo"),
    new quote("It is not enough to have a good mind. The main thing is to use it well.", "Rene Descartes"),
    new quote("Shoot for the moon, even if you fail, you'll land among the stars", "Cecelia Ahern"),
    new quote("The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.", "Mark Twain"),
    new quote('Instead of worrying about what you cannot control, shift your energy to what you can create.','Roy T. Bennett'),
    new quote("In the midst of life, we are in death.","Agatha Christie"),
    new quote("When we are no longer able to change a situation, we are challenged to change ourselves.", "Victor Frankl"),
    new quote("People say nothing is impossible, but I do nothing every day.", "A.A. Milne"),
    new quote("All that we see or seem is but a dream within a dream.", 'Edgar Allan Poe'),
    new quote("Fools rush in where angels fear to tread.", "Alexander Pope"),
    new quote("The first duty of a man is to think for himself", "Jose Marti"),
    new quote('Our greatest glory is not in never falling, but in rising every time we fall.','Confucius'),
    new quote("Yesterday is but today's memory, and tomorrow is today's dream.",'Khalil Gibran'),
    new quote("A day without laughter is a day wasted.", "Nicolas Chamfort"),
    new quote("You me or nobody is going to hit as hard as life. But it ain't about how hard you hit. It's about how hard you can get hit and keep moving forward","Rocky Balboa"),
    new quote("It is the mark of an educated mind to be able to entertain a thought without accepting it.","Aristotle"),
    new quote("Common sense ain't common.", "Will Rogers"),
    new quote("What saves a man is to take a step. Then another step.","Antoine de Saint-Exupery"),
    new quote("The heights charm us, but the steps do not; with the mountain in our view we love to walk the plains.", "Johann Wolfgang von Goethe"),
    new quote("The road to success is dotted with many tempting parking spaces.", "Will Rogers"),
    new quote("I don't like work--no man does--but I like what is in the work--the chance to find yourself. Your own reality--for yourself not for others--what no other man can ever know. They can only see the mere show, and never can tell what it really means.", "Joseph Conrad"),
    new quote('Defeat, my Defeat, my solitude and my aloofness. You are dearer to me than a thousand triumphs, and sweeter to my heart than all world-glory.','Khalil Gibran'),
    new quote("Your strength is just an accident arising from the weakness of others.", "Joseph Conrad"),
    new quote("Adversity makes men and prosperity makes monsters.", "Victor Hugo"),
    new quote("Life's battles don't always go to the stronger or faster man; But soon or late the man who wins is the man who thinks he can.", "Walter D. Wintle"),
    new quote("No dark fate determines the future. We do.","Dalai Lama"),
    new quote('One day, in retrospect, the years of struggle will strike you as the most beautiful.','Sigmund Freud'),
    new quote("Time is too slow for those who wait, too swift for those who fear, too long for those who grieve, too short for those who rejoice, but for those who love, time is eternity.","Henry Van Dyke"),
    new quote("Not one of us can rest, be happy, be at home, be at peace with ourselves, until we end hatred and division.", "John Lewis"),
    new quote('Life can only be understood backwards; but it must be lived forwards.','Soren Kierkegaard'),
    new quote("Most men die at 27, we just bury them at 72.","G.E. Marchand"),
    new quote("What makes the desert beautiful is that somewhere it hides a well.","Antoine de Saint-Exupery"),
    new quote("In the midst of chaos, there is also opportunity.", "Sun Tzu"),
    new quote("Risks must be taken because the greatest hazard in life is to risk nothing.", "Leo F. Buscaglia"),
    new quote("All in the valley of Death; Rode the six hundred.","Alfred Tennyson"),
    new quote("Motivation gets you going and habit gets you there.", "Zig Ziglar"),
    new quote("Tell me and I forget. Teach me and I remember. Involve me and I learn.","Benjamin Franklin"),
    new quote("In the course of my life, I have often had to eat my words, and I must confess that I have always found it a wholesome diet.", "Winston Churchill"),
    new quote("All men make mistakes, but a good man yields when he knows his course is wrong, and repairs the evil. The only crime is pride.","Sophocles"),
    new quote("Two wrongs don't make a right, but they make a good excuse.", "Thomas Szasz"),
    new quote("Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.","Marcus Aurelius"),
    new quote("To be or not to be that is the question", "William Shakespeare"),
    new quote("Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.","Antoine de Saint-Exupery"),
    new quote('Is it better for a man to have chosen evil than to have good imposed upon him?','Anthony Burgess'),
    new quote('I did not have sexual relations with that woman','Bill Clinton'),
    new quote("Tension is who you think you should be. Relaxation is who you are.","Unknown"),
    new quote("I am the master of my fate, I am the captain of my soul.", "William Ernest Henley"),
    new quote("Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", "Rumi"),
    new quote("It is always darkest just before the dawn.", "Thomas Fuller"),
    new quote('To belittle you have to be little','Khalil Gibran'),
    new quote('The beginnings of all things are small.','Unknown'),
    new quote('The secret of life, though, is to fall seven times and to get up eight times.','Paulo Coelho'),
    new quote("Life would be tragic if it weren't funny.", "Stephen Hawking"),
    new quote("If I had nine hours to chop down a tree, I'd spend the first six sharpening my axe","Abraham Lincoln"),
    new quote("Facts do not cease to exist because they are ignored.", "Aldous Huxley"),
    new quote("Solitude has soft, silky hands, but with strong fingers it grasps the heart and makes it ache with sorrow.","Khalil Gibran"),
    new quote("It's no use going back to yesterday, because I was a different person then.", "Lewis Carroll"),
    new quote("He who opens a school door closes a prison.", "Victor Hugo"),
    new quote("The eyes of others our prisons; their thoughts our cages.", "Virginia Woolf"),
    new quote('People demand freedom of speech as a compensation for the freedom of thought which they seldom use.','Soren Kierkegaard'),
    new quote("Peace begins with a smile", "Mother Teresa"),
    new quote("The way to get started is to quit talking and begin doing.","Walt Disney"),
    new quote("There is nothing more powerful than an idea whose time has come.", "Victor Hugo"),
    new quote("You can avoid reality, but you can't avoid the consequences of avoiding reality.","Ayn Rand"),
    new quote("This is the way the world ends. Not with a bang but a whimper.", "T.S. Eliot"),
    new quote("Thinking is difficult, that's why most people judge.",'Carl Gustav Jung'),
    new quote("Conquer yourself rather than the world.", "Rene Descartes"),
    new quote("Life is like a boxing match; defeat is declared not when you fall but when you refuse to stand again.", "Unknown"),
    new quote("I like things to happen, and if they don't happen I like to make them happen.",'Winston Churchill'),
    new quote('One drop of truth can outweigh an ocean of lies', 'Aleksandr Solzhenitsyn'),
    new quote("Imaginary evil is romantic and varied; real evil is gloomy, monotonous, barren, boring. Imaginary good is boring; real good is always new, marvelous, intoxicating.","Simone Weil"),
    new quote("He who wishes to be obeyed must know how to command","Niccolo Machiavelli"),
    new quote("Never miss a good chance to shut up.", "Will Rogers"),
    new quote("Where the telescope ends the microscope begins, and who can say which has the wider vision?", "Victor Hugo"),
    new quote("Fortune is not on the side of the faint-hearted.","Sophocles"),
    new quote("Not all those who wander are lost.", "J.R.R. Tolkien"),
    new quote('The safest way of not being very miserable is not to expect to be very happy.','Arthur Schopenhauer'),
    new quote("Perhaps one did not want to be loved so much as to be understood.", "George Orwell"),
    new quote('To live is to suffer, to survive is to find some meaning in the suffering.','Friedrich Nietzsche'),
    new quote("Do you want to know who you are? Don't ask. Act! Action will delineate and define you.", "Thomas Jefferson"),
    new quote("It's not the load that breaks you down, it's the way you carry it.", "Lou Holtz"),
    new quote("A star can never die. It just turns into a smile and melts back into the cosmic music, the dance of life.","Michael Jackson"),
    new quote('We know what we are, but not what we may be.','William Shakespeare'),
    new quote("Be yourself; everyone else is already taken.", "Oscar Wilde"),
    new quote("A goal without a plan is just a wish","Antoine de Saint-Exupery"),
    new quote("If there are no dogs in Heaven, then when I die I want to go where they went.","Will Rogers"),
    new quote("Don't dismiss the desires of the mind. Look at those desires. Go deeply into those desires. And behind each desire, you will find only one desire — the desire to be free.","Acharya Prashant"),
    new quote("Your attitude, not your aptitude, will determine your altitude.","Zig Ziglar"),
    new quote("I wouldn't call myself a fan of steampunk, but I will say it is the healthiest way to prepare punk.","Bobby Lee"),
    new quote("Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"),
    new quote("To dare is to momentarily lose one's footing. Not to dare is to lose oneself.","Soren Kierkegaard"),
    new quote("The life of the dead is set in the memory of the living.","Marcus Tullius Cicero"),
    new quote("Our memory is a more perfect world than the universe: it gives back life to those who no longer exist.","Guy de Maupassant"),
    new quote("Behind every successful man there's a lot of unsuccessful years.","Bob Brown"),
    new quote("I don't hate myself. I hate that I cannot be myself.","Unknown"),
    new quote("There is no worse blind man than one who isn't willing to see.","Unknown"),
    new quote("Difficult roads lead to beautiful destinations.","Frances de Amor"),
    new quote("We avenge intellect when we dupe a fool, and it is a victory not to be despised.", "Giacomo Casanova"),
    new quote("A relit cigarette never tastes the same and that's all I'll preach on rekindling old flames.","Unknown"),
    new quote("Opportunity does not knock, it presents itself when you beat down the door.","Kyle Chandler"),
    new quote("I sat with my anger long enough until she told me her real name was grief.","C.S. Lewis"),
    new quote("I never lose: either I win, or I learn.","Nelson Mandela"),
    new quote("Life is so short, Forgetting is so long.","Pablo Neruda"),
    new quote("The only way to get rid of a temptation is to yield to it.","Oscar Wilde"),
    new quote("Dripping water hollows out stone, not through force, but through persistence.","Ovid"),
    new quote("If you fell down yesterday, stand up today."," H. G. Wells"),
    new quote("I personally am a workaholic. For many years I was hopelessly addicted to workahol.","Norm Macdonald"),
    new quote("At 18 our convictions are hills from which we look; At 45 they are caves in which we hide.","F. Scott Fitzgerald"),
    new quote("I became insane, with long intervals of horrible sanity.","Edgar Allan Poe"),
    new quote("What are people? - your perception of their actions.","Unknown"),
    new quote("A champion is someone who gets up when he can't.", "Jack Dempsey"),
    new quote("For every man the world is as fresh as it was at the first day, and as full of untold novelties for him who has the eyes to see them.","T. H. Huxley"),
    new quote("I'd rather have a bottle in front of me than a frontal lobotomy.","Tom Waits"),
    new quote("I was destined by nature to become a diplomat: I was born on the first April.","Otto von Bismarck"),
    new quote("Whatever you do, always give 100%. Unless you're donating blood.","Bill Murray"),
    new quote("All grown-ups were once children but only a few of them remember it.","Antoine de Saint-Exupery"),
    new quote("Believe you can and you're halfway there.","Theodore Roosevelt"),
    new quote("Happiness is an allegory, unhappiness is a story.","Leo Tolstoy"),
    new quote("There is freedom of speech, but I cannot guarantee freedom after speech.","Idi Amin"),
    new quote("The broken will always be able to love harder than most. Once you've been in the dark, you learn to appreciate everything that shines.","Unknown"),
    new quote("We suffer more in imagination than reality.","Seneca"),
    new quote("Strange as it seems, no amount of learning can cure stupidity, and higher education positively fortifies it.","Stephen Vizinczey"),
    new quote("We live in a fantasy world, a world of illusion. The great task in life is to find reality.","Iris Murdoch"),
    new quote("My father was brutally murdered last week, and it's only now that I can look back and laugh.","Norm Macdonald"),
    new quote("One can loosen their morals, but one mustn't loosen their conscience.","Kumar Ashutosh"),
    new quote("Life is really simple, but we insist on making it complicated.","Confucius"),
    new quote("The search for happiness is one of the chief sources of unhappiness.","Eric Hoffer"),
    new quote("The sweetest songs are those that tell of the saddest thoughts.","Percy Shelley"),
    new quote("One idiot is one idiot. Two idiots are two idiots. Ten thousand idiots are a political party.","Unknown"),
    new quote("Do not lower your goals to the level of your abilities. Instead, raise your abilities to the height of your goals.","Swami Vivekananda"),
    new quote("Don't spend time beating on a wall, hoping to transform it into a door.","Coco Chanel"),
    new quote("You must trust and believe in people or life becomes impossible.","Anton Chekhov"),
    new quote("A person is never happy except at the price of some ignorance.","Anatole France"),
    new quote("You are free and that is why you are lost.","Franz Kafka"),
    new quote("Concentrate all your thoughts upon the work in hand. The sun's rays do not burn until brought to a focus.","Alexander Graham Bell"),
    new quote("Never test the depth of river with both feet.","Warren Buffett"),
    new quote("A boy becomes a man by his responsibilities, not his age.","Unknown"),
    new quote("Some problems don't have solutions, only outcomes.","Isaac Asimov"),
    new quote("The wise can change their minds. The stubborn, never.","Immanuel Kant"),
    new quote("Life is something that everyone should try at least once.","Henry J. Tillman"),
    new quote("Books are mirrors: you only see in them what you already have inside you.","Carlos Ruiz Zafón"),
    new quote("You will face many defeats in life, but never let yourself be defeated.","Maya Angelou"),
    new quote("It is not true that equality is a law of nature. Nature has made nothing equal.","Luc de Clapiers"),
    new quote("Give a man a fish and you feed him for a day. Teach him how to fish and you feed him for a lifetime.","Unknown"),
    new quote("What I hear, I forget. What I say, I remember. What I do, I understand.","Xun Kuang"),
    new quote("If you care what people think, you will always be their prisoner.","Unknown"),
    new quote("Nobility is defined by the demands it makes on us — by obligations, not by rights.","Jose Ortega y Gasset"),
    new quote("To say 'I don't have time', is like saying, 'I don't want to'","Lao Tzu"),
    new quote("Of all sad words of mouth or pen, the saddest are these: 'It might have been'.","John Greenleaf Whittier"),
    new quote("If you want to build a ship, don't drum up the men to gather wood, divide the work and give orders. Instead, teach them to yearn for the vast and endless sea.","Antoine de Saint-Exupery"),
    new quote("The child who is not embraced by the village will burn it down to feel its warmth","Unknown"),
    new quote("We judge ourselves by our intentions and others by their actions.","Stephen Covey"),
    new quote("When you have a dream, you've got to grab it and never let go.","Carol Burnett"),
    new quote("The bad news is time flies. The good news is you're the pilot.","Michael Altshuler"),
    new quote("Keep your face always toward the sunshine, and shadows will fall behind you.","Walt Whitman"),
    new quote("What you get by achieving your goals is not as important as what you become by achieving your goals.","Zig Ziglar"),
    new quote("All dreams are within reach. All you have to do is keep moving towards them.","Viola Davis"),
    new quote("I can't change the direction of the wind, but I can adjust my sails to always reach my destination.","James Dean"),
    new quote("Limit your 'always' and your 'nevers.'","Amy Poehler"),
    new quote("When you know what you want, and want it bad enough, you'll find a way to get it","Jim Rohn"),
    new quote("Don't be afraid to give up the good for the great.","John D. Rockefeller"),
    new quote("We generate fears while we sit. We overcome them by action.","Dr. Henry Link"),
    new quote("When you want to fool the world, tell the truth.","Otto von Bismark"),
    new quote("To joke in the face of danger is the supreme politeness, a delicate refusal to cast oneself as a tragic hero.","Edmond Rostand"),
    new quote("I suppose it is tempting, if the only tool you have is a hammer, to treat everything as if it were a nail.","Abraham Maslow"),
    new quote("A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools.","Douglas Adams"),
    new quote("When bad fortune occurs, the unresourceful, unimaginative man looks about him to attach the blame to someone else; the resolute accepts misfortune and endeavors to survive, mature, and improve because of it.","Anne McCaffrey"),
    new quote("Anyone who has ever looked into the glazed eyes of a soldier dying on the battlefield will think hard before starting a war.","Otto von Bismarck"),
    new quote("Whether it is happy or unhappy, a man's life is the only treasure he can ever possess.","Giacomo Casanova"),
    new quote("Truth is on the march, and nothing will stop it.","Emile Zola"),
    new quote("You see, war is not the answer; For only love can conquer hate.","Marvin Gaye"),
    new quote("We shall be judged by what we do, not by how we felt while we were doing it.","Kenneth Tynan"),
    new quote("Man is the only animal that laughs and weeps, for he is the only animal that is struck with the difference between what things are, and what they might have been.","William Hazlitt"),
    new quote("I am only one, But still I am one. I cannot do everything, But still I can do something; And because I cannot do everything; I will not refuse to do the something that I can do.","Edward Everett Hale"),
    new quote("Humanity will ever seek but never attain perfection. Let us at least survive and go on trying.","Dora Russell"),
    new quote("The most important thing is to actually think about what you do. To become aware and actually think about the effect of what you do on the environment and on society. That's key, and that underlies everything else.","Jane Goodall"),
    new quote("Where there is great love there are always miracles.","Willa Cather"),
    new quote("There must be a beginning of any great matter, but the continuing unto the end until it be thoroughly finished yields the true glory.","Francis Drake"),
    new quote("He who learns must suffer And even in our sleep pain that cannot forget","Aeschylus"),
    new quote("All we are saying is give peace a chance.","John Lennon"),
    new quote("If any man seeks for greatness, let him forget greatness and ask for truth, and he will find both.","Horace Mann"),
    new quote("Veracity is the heart of morality.","T. H. Huxley"),
    new quote("Once you label me you negate me.","Soren Kierkegaard"),
    new quote("That best portion of a good man's life, — His little, nameless, unremembered acts of kindness and of love.","William Wordsworth"),
    new quote("If you shut your door to all errors truth will be shut out.","Rabindranath Tagore"),
    new quote("Being entirely honest with oneself is a good exercise.","Sigmund Freud"),
    new quote("All shall be well, I'm telling you, let the winter come and go; All shall be well again, I know.","Sydney Carter"),
    new quote("The secret of liberty is to enlighten men, as that of tyranny is to keep them in ignorance.","Maximilien Robespierre"),
    new quote("If I can stop one heart from breaking, I shall not live in vain; If I can ease one life the aching, Or cool one pain, Or help one fainting robin Unto his nest again, I shall not live in vain.","Emily Dickinson"),
    new quote("There are very few human beings who receive the truth, complete and staggering, by instant illumination. Most of them acquire it fragment by fragment, on a small scale, by successive developments, cellularly, like a laborious mosaic.","Anais Nin"),
    new quote("If they can get you asking the wrong questions, they don't have to worry about answers.","Thomas Pynchon"),
    new quote("Freedom granted only when it is known beforehand that its effects will be beneficial is not freedom.","Friedrich Hayek"),
    new quote("Life is a long lesson in humility.","J. M. Barrie"),
    new quote("Man is a substantial emigrant on a pilgrimage of being, and it is accordingly meaningless to set limits to what he is capable of being.","José Ortega y Gasset"),
    new quote("The world is more malleable than you think and it's waiting for you to hammer it into shape.","Bono"),
    new quote("Exercise should be regarded as tribute to the heart.","Gene Tunney"),
    new quote("Nobody owes anybody a living, but everybody is entitled to a chance.","Jack Dempsey"),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("",""),
    new quote("A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say, we did it ourselves","Lao Tzu"),
    //new quote("",""),
    ]       
   
}


//returns quote_list to motivational_quote
export function Return_quote_list(index) {
    return quotes_list[index];
}

//Returns list length
export function Return_quote_list_length() {
    return quotes_list.length;
}
